### ISSUE TITLE
Out of date.

### ISSUE THREAD

**Issue by daddy32** [cem/gogs-sandstorm#16]
Latest changes from original seem to have been merged about 18 months ago.
How much work would be required to bring this up to date and distribute the current version on Sandstorm App Market?

**Comment by eubyte** [comment]
Yes... Can you please update Gogs in the Sandstorm App Market to the most current version. Thank you!

**Comment by ocdtrekkie** [comment]
Probably the best way to get an updated version is to look into updating the package yourself. As it hasn't been updated by the package owner in nearly two years.

**Comment by cem** [comment]
I'm here and alive. I will start updating this package tonight since I have some free time.

**Comment by ocdtrekkie** [comment]
Oh, awesome! @cem if you have any issues with vagrant-spk, hit me up. The old Vagrant box is gone, so we've got some updated commits in master to use a newer box. If you have your old build environment though it may work fine.

**Comment by eubyte** [comment]
Thank you @cem -- much appreciated!

**Comment by ocdtrekkie** [comment]
Note that either of you can find the unapproved version here on the experimental market: https://apps.sandstorm.io/app/d9ygf47xrtnw12j92cyt6cu8ut75esx01u4q3kcrn8415w9qzzgh?experimental=true

I will try to find time to review it ASAP.

**Comment by ocdtrekkie** [comment]
Reviewed, approved, and live on the market. https://apps.sandstorm.io/app/d9ygf47xrtnw12j92cyt6cu8ut75esx01u4q3kcrn8415w9qzzgh

**Comment by ocdtrekkie** [comment]
@cem FYI, your contact email bounces.

**Comment by daddy32** [comment]
Thank you all very much! 
I've installed the experimental version and everything seems to be fine.
The official released version (found on market or through the link above) still seems to be the older one.

**Comment by ocdtrekkie** [comment]
@daddy32 Git push is broken on it. Sorry I didn't ping that here. :( #17

**Comment by ocdtrekkie** [comment]
@daddy32 There is now a new version in the experimental market that can git push. It will probably be approved in a couple hours.

**Comment by ocdtrekkie** [comment]
Fixed release approved, this issue can be closed. :D
