### ISSUE TITLE
Create "New Migration" missing

### ISSUE THREAD

**Issue by ghost** [cem/gogs-sandstorm#19]
Hi, 

is there a reason why Gogs installed via Sandstorm doesn't have option to create new mirror (aka. "New migration")?

![image](https://user-images.githubusercontent.com/33389377/44090958-8c370e02-9fd4-11e8-87c1-2e5b89fedd7f.png)

**Comment by ocdtrekkie** [comment]
My assumption would be that it wouldn't work inside the Sandstorm sandbox, since the server is not permitted to reach out to arbitrary third party servers. (It's probable that a way does exist to enable this now, but it would require someone to write the requisite code to do it.)

**Comment by ghost** [comment]
Ok, I may get into this after I have more experience with Sandstorm sandbox.
