### ISSUE TITLE
Not possible to upload organization avatar

### ISSUE THREAD

**Issue by xet7** [cem/gogs-sandstorm#4]
Hi,
in Gogs, when using Sandstorm I installed on one server, and I try to upload organization avatar, it says "UploadAvatar: open /opt/app/gogs/data/avatars/2: no such file or directory"

And when I try to add file there manually (should not be needed) it says "UploadAvatar: open /opt/app/gogs/data/avatars/2: read-only file system"

This is because at https://docs.sandstorm.io/en/latest/developing/troubleshooting/ it says "Read-only filesystem" : Only the /var directory is writable; the rest of the filesystem (which contains the contents of your app package) is read-only. If your app wants to write to locations other than /var, and it's not easy to change the app's code, one work-around is to create a symlink from the location you app wants to modify to a location under /var. This won't work for all applications however.

In Gogs settings, there is place where data directory location could be defined.

Also because currently this port is behing official https://github.com/gogits/gogs version, I have talked with Gogs devs at https://gitter.im/gogits/gogs if they could help to get this project updated and added to official project.

**Comment by pgrm** [comment]
same issue - would be cool to have an official version ....

**Comment by xet7** [comment]
@pgrm I chatted with Gogs devs, they like the idea of Sandstorm but they don't have time to get familiar with Sandstorm to make required fixes, so I said that when I get more familiar with Sandstorm I could try to do required changes and submit pull request to Gogs. Although no promises and no fixed timetable yet. I think it's more important for core Gogs devs to concentrate to implement highly requested features such as Gogs API and GitHub issue import.

**Comment by cem** [comment]
Should be fixed as of the latest version on Sandstorm (0.8.23.0126).
