### ISSUE TITLE
404 errors for single issue js and css files

### ISSUE THREAD

**Issue by niko** [cem/gogs-sandstorm#5]
(is this the repo of the official sandstorm.io gogs grain? and is this the right place to file issues for it?)

I get the following errors in the js console when loading a single issues page in a new gogs grain:

```
GET https://3ad....oasis.sandstorm.io/css/dropzone-4.2.0.css 
1:474
GET https://3ad....oasis.sandstorm.io/js/libs/dropzone-4.2.0.js 
gogs.js?v=de55b11d34e3d22d20f423b475711511:839
Uncaught ReferenceError: Dropzone is not defined
```

As a result most issue specific JS functionality won't work such as editing the issue, editing a comment, assigning a label, milestone or assignee.

I couldn't find any issue with this description in the [gogs repo](https://github.com/gogits/gogs/issues), so I assume it's only an issue with the sandstorm port.

**Comment by xet7** [comment]
@niko Yes this is sandstorm port of Gogs, port modifications made by @cem . So this is correct place for issues in sandstorm port. It something works on official Gogs, but not Sandstorm port, then it's problem with Sandstorm port. Please test both versions if possible.

**Comment by niko** [comment]
Work's fine on a local installation. Seems to be a bug in the sandstorm port.

**Comment by cem** [comment]
I pushed a new Gogs version (0.9.13) to the Sandstorm app market. I cannot reproduce this with the new version. Please open another issue if you still have the same error.
