### ISSUE TITLE
Code Not Showing When Comparing Changes for Pull Request

### ISSUE THREAD

**Issue by eyedarts** [cem/gogs-sandstorm#7]
<img src="https://eogdprgfetp179dmm4ac.oasis.sandstorm.io/pull_request_diff_screenshot.png">

As you can see, none of the code comparison is visible when attempting to compare differences between two branches in order to make a pull request between Gogs/Sandstorm users.

I am able to view the diffs when I click on specific commits.

Is this something specific to my setup? I'm self-hosting a Sandstorm instance. I've tried resetting the grain and am still getting the same issue. Let me know if I can provide more details in order to help solve this problem.

EDIT: After submitting the pull request, the code is visible in the "Files Changed" tab. So, this seems to be a problem viewing the changes while creating the pull request.

**Comment by cem** [comment]
I pushed a new Gogs version (0.9.13) to the Sandstorm app market. I cannot reproduce this with the new version. Please open another issue if you still have the same error.
