### ISSUE TITLE
Merging same-repo pull request returns Gogs 500 error page

### ISSUE THREAD

**Issue by DevonStrawn** [cem/gogs-sandstorm#9]
First, thanks for writing gogs-sandstorm - it's the whole reason I looked into Sandstorm in the first place. It's wonderful!

Not sure if this is a Gogs bug or Gogs-sandstorm, but Google didn't turn up anything for the error below, and it seems like the sort of thing that might trip up Sandstorm / Gogs.

Repro steps:
1. setup a Git repo with at least one branch in Gogs
2. create a pull request from one of the branches into master
3. in the pull request page, click "Merge Pull Request" button

Bug: Gogs 500 error pages appear:

![image](https://cloud.githubusercontent.com/assets/1132600/14407326/0d890082-fe79-11e5-9f17-48132475d2e6.png)

Here's the relevant bit of debug log (something about "unable to look up current user in the passwd file: No such file or directory"):

![image](https://cloud.githubusercontent.com/assets/1132600/14407309/77eb922e-fe78-11e5-9bf1-5b6da54406cc.png)

(using the latest v0.9.13 Gogs Sandstorm app)

Note that this depends on Gogs' new feature of [same-repository Pull Requests](https://github.com/gogits/gogs/issues/1597).

**Comment by cem** [comment]
> First, thanks for writing gogs-sandstorm - it's the whole reason I looked into Sandstorm in the first place. It's wonderful!

I'm very happy to hear that!

I pushed a fix for this issue (v0.9.13.fix1). Please open another issue if this isn't resolved.
